name: mega
version: 0.1.0.0

extra-source-files:
  - README.md
  - ChangeLog.md

dependencies:
  - base >= 4.7 && < 5
  - containers
  - mtl
  - megaparsec
  - text
  - exceptions
  - random
  - transformers

executables:
  mega-exe:
    main: Main.hs
    source-dirs: src
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
